sudo: required
services: 
  - docker

before-install: 
  - docker build -t jeevanbs/docker-react -f docker.dev .

script:
  - 
  - docker run jeevanbs/docker-react npm run test -- --coverage

#deploy:
 # provider: elasticbeanstalk
  #region: ""
  #app: "docker-react"
  #env: "docker-react-env"
  #bucket_name: ""
  #bucket_path: "docker-react"
  #on:
   # branch: master